### ISSUE TITLE
How to download a full temporal series from a station?

### ISSUE THREAD

**Issue by ajpelu** [emf-creaf/meteospain#12]
Thanks for this amazing pkg. 

I've tried to download a full temporal data series from one AEMET's station, because I need to explore all the temporal evolution of precipitación for a location closed to a station. 
I know that there are some limitations using the AEMEET API (e.g. limited maximum of requests; request date up to 1 month;... )

So, do you know if there is a way to download the complete data series of a weather station?

I wrote a piece of code (not elegant but functional) that could work:

```
library(meteospain) 
# Create a sequence of months intervals (to solve the date's limitation) 
meses <- seq.Date(as.Date('1980-01-01'), as.Date('2022-01-01'), "months")

out <- data.frame()
for (i in 1:length(meses)){
  try({ # to skip the errors due to no data in the query 
  aemet_options <- aemet_options(resolution = "daily", 
                                 start_date = meses[i], 
                                 end_date = meses[i+1], 
                                 stations = "6325O",
                                 api_key = k) # note that k is not provided 

  d <- get_meteo_from('aemet', aemet_options) 

  out <- rbind(out,d)}
  )
}
```
 
To get the temporal series (nrows = 20373 rows) I took me more than 2 hours, so definitively is not efficient (I know that is by API limitation), but, do you know any faster way to obtain the full data series from one (of several) stations? 

Another related question. Is there any way to know the first (and last) record of a station? Maybe a small function evaluating this information (i.e. first and last date of each record -for each variable- for the stations) could be useful. 

Thanks

**Comment by MalditoBarbudo** [comment]
@ajpelu 
In the docs, you have examples for loops, very similar to the one you have wrote:
https://emf-creaf.github.io/meteospain/articles/api_limits.html
For now is the only option to get all the data due to limits imposed by the APIs. You can try to parallelize, but, at least with AEMET, in my tests parallelizing requests hits the request per second limit too often, having to wait anyways for a cooldown.

About the first and last values for a station, if I remember correctly this information is not available from the API directly, and doing it on  the R side involves or downloading all the series to determine start and end (which takes too much time) or using some kind of sampliing algorithm. Both takes time and API requests, which can be problematic for some APIs like meteocat, where they are limited per month.

**Comment by ajpelu** [comment]
@MalditoBarbudo thanks for the quick response. 
I've missed the examples. Thanks for the documentation. 

About the last issue. You're right. Maybe I'll contact AEMET-API developers to suggest those parameters in the API, but my previous experience was not good (I did not receive an answer)
Thanks a lot
